### ISSUE TITLE
Flicker / flashing when running on desktop

### ISSUE THREAD

**Issue by stuaxo** [davidedc/raspberry-pi-autoVj#7]
Was running on the desktop, (via pygame), there seems to be really harsh bright flashes a few times a second, is it meant to do this ?

Haven't tested on pi yet.

**Comment by paddywwoof** [comment]
Stuart, the project evolved quite a bit after it was moved to devart-template with some increased "subtlety", however we made a conscious decision that the theme should be shocking and garish which is reflected in the shaders as well. You could tone it down reasonably easily.

Unfortunately, cloning the devart-template lands you with a load of peripheral stuff that is really only there for our submission for the competition. (you might be able to do a variation of "wget https://github.com/davidedc/devart-template/raw/master/project_code/.." but I don't know how to get more than one file at a time)

**Comment by stuaxo** [comment]
Ah, OK ... I saw https://github.com/davidedc/devart-template and because the README isn't initialised, so I assumed there was no project in it.

If it's _meant_ to do that, then that's fine :)

I'll just checkout the whole thing and have a play with it.

**Comment by davidedc** [comment]
yep intentionally over the top :-) also see gifs and pics in here:
http://www.davidedc.com/raspberry-pi-autovj-2013/
